export const adminTypes = {
  // Dashboard type
  GET_DASHBOARD_DATA_PENDING: "GET_DASHBOARD_DATA_PENDING",
  GET_DASHBOARD_DATA_SUCCESS: "GET_DASHBOARD_DATA_SUCCESS",
  GET_DASHBOARD_DATA_FAILED: "GET_DASHBOARD_DATA_FAILED",
};
